# fly.toml app configuration file generated for petsitter-project-silent-grass-3611 on 2024-05-20T09:54:38+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'petsitter-project'
primary_region = 'jnb'

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  SUPABASE_URL = "https://uurxrpllqveasuvnxuns.supabase.co"
  SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cnhycGxscXZlYXN1dm54dW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4NDQ3NjgsImV4cCI6MjAzMTQyMDc2OH0.j-rcZtRWkEZozE5OouYyoaoIGYCD_m7xyyky0g4Lz_c"
  SESSION_SECRET = "TOPSECRETWORD"
  ETHEREAL_HOST = "smtp.ethereal.email"
  ETHERIAL_PORT = "587"
  ETHEREAL_USER ="ramona.satterfield@ethereal.email"
  ETHERIAL_PASSWORD ="vt8zVYr3j4aCAMWVdZ"
  

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
    protocol = "tcp"
  script_checks = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
