# fly.toml app configuration file generated for nsr-pro-construction on 2024-07-04T23:23:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nsr-pro-construction'
primary_region = 'jnb'



[build]
builder = "paketobuildpacks/builder:base"

[env]
  SUPABASE_URL=https://uurxrpllqveasuvnxuns.supabase.co
  SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1cnhycGxscXZlYXN1dm54dW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4NDQ3NjgsImV4cCI6MjAzMTQyMDc2OH0.j-rcZtRWkEZozE5OouYyoaoIGYCD_m7xyyky0g4Lz_c
  SESSION_SECRET ="TOPSECRETWORD"
  ETHEREAL_HOST='smtp.ethereal.email'
  ETHERIAL_PORT=587
  ETHEREAL_USER='ramona.satterfield@ethereal.email'
  ETHERIAL_PASSWORD='vt8zVYr3j4aCAMWVdZ'
  EMAIL_USER='jaunn21@gmail.com'
  NODEMAILER_PASSWORD='gztb liau mryu oujq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
